REDIS_PRIMARY_KEY_PATTERN = '{index}-{primary}'
REDIS_PRIMARY_DEFAULT_INCR_KEY = '{index}-incr'
REDIS_INDEX_PATTERN = '{index}-index-{key_value_pair}'
REDIS_PRIMARY_FOREIGN_KEY_PATTERN = '{index}-foreign-{primary}-{foreign_key}'
REDIS_FOREIGN_PRIMARY_KEY_PATTERN = '{index}-foreign-{foreign_key_value_pair}'
REDIS_FOREIGN_COUNT = '{index}-foreign-{foreign_key_value_pair}_count'
REDIS_FOREIGN_SIZE = '{index}-foreign-{foreign_key_value_pair}_size'
REDIS_FOREIGN_PARTITION = '{index}-foreign-{foreign_key_value_pair}_partition'
REDIS_UNIQUE_PATTERN = '{index}-unique-{key_value_pair}'

DEFAULT_PRIMARY_KEY = 'id'
UNIQUE_TOGETHER = 'unique_together'
CONCRETE_FIELDS = 'concrete_fields'
PRIMARY_KEY = 'primary_key'
UNIQUE_KEYS = 'unique_keys'
FOREIGN_KEYS = 'foreign_keys'
INDEXES_KEYS = 'indexes'
